apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: login
  namespace: bastion
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: login
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gate
  namespace: bastion
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: gate
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: game-shard
  namespace: bastion
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: game-shard
