// NewGame 跨服务 HTTP/JSON 与 NATS 消息定义。
// Gate TCP 二进制帧（cmd/act）见 pkg/protocol；HTTP 路由见 pkg/protocol/http_api.go。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LoginRequest POST /api/login 请求体。
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // 用户名；不存在则自动注册
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // 明文密码（传输层应使用 HTTPS）
	ZoneId        int32                  `protobuf:"varint,3,opt,name=zone_id,proto3" json:"zone_id,omitempty"`  // 目标区服 ID，如 1、2
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetZoneId() int32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

// LoginResponse POST /api/login 响应体。
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`          // 0=成功；1001 参数错；1002 密码错
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`         // 会话令牌，Gate CmdLogin 时使用
	RoleId        int64                  `protobuf:"varint,3,opt,name=role_id,proto3" json:"role_id,omitempty"`    // 该区服角色 ID
	GateAddr      string                 `protobuf:"bytes,4,opt,name=gate_addr,proto3" json:"gate_addr,omitempty"` // Gate TCP 地址，如 127.0.0.1:9000
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`     // 可读说明
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *LoginResponse) GetGateAddr() string {
	if x != nil {
		return x.GateAddr
	}
	return ""
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// EnterGateRequest Gate TCP CmdLogin(1) ActLogin(1) 的 JSON 载荷。
type EnterGateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // Login 返回的 token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterGateRequest) Reset() {
	*x = EnterGateRequest{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterGateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterGateRequest) ProtoMessage() {}

func (x *EnterGateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterGateRequest.ProtoReflect.Descriptor instead.
func (*EnterGateRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *EnterGateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// MatchRequest POST /api/match/join 请求体。
type MatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,proto3" json:"role_id,omitempty"` // 匹配角色 ID
	Mode          int32                  `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`       // 匹配模式，默认 0
	ZoneId        int32                  `protobuf:"varint,3,opt,name=zone_id,proto3" json:"zone_id,omitempty"` // 角色区服；跨服匹配时必填
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRequest) Reset() {
	*x = MatchRequest{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRequest) ProtoMessage() {}

func (x *MatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRequest.ProtoReflect.Descriptor instead.
func (*MatchRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *MatchRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *MatchRequest) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *MatchRequest) GetZoneId() int32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

// MatchResponse POST /api/match/join 响应体。
type MatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`        // 0=成功；5000 匹配/建房失败
	MatchId       string                 `protobuf:"bytes,2,opt,name=match_id,proto3" json:"match_id,omitempty"` // 匹配 ID；等待中为 wait_{role_id}
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,proto3" json:"room_id,omitempty"`   // Battle 房间 ID；未凑满人为空
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchResponse) Reset() {
	*x = MatchResponse{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResponse) ProtoMessage() {}

func (x *MatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResponse.ProtoReflect.Descriptor instead.
func (*MatchResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *MatchResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MatchResponse) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// BattleRoomCreateRequest POST /api/battle/room/create 请求体（Match 内部调用）。
type BattleRoomCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []int64                `protobuf:"varint,1,rep,packed,name=members,proto3" json:"members,omitempty"` // 至少 2 名玩家 role_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleRoomCreateRequest) Reset() {
	*x = BattleRoomCreateRequest{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleRoomCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleRoomCreateRequest) ProtoMessage() {}

func (x *BattleRoomCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleRoomCreateRequest.ProtoReflect.Descriptor instead.
func (*BattleRoomCreateRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *BattleRoomCreateRequest) GetMembers() []int64 {
	if x != nil {
		return x.Members
	}
	return nil
}

// BattleRoomCreateResponse POST /api/battle/room/create 响应体。
type BattleRoomCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 0=成功
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,proto3" json:"room_id,omitempty"` // 战斗房间 ID，如 br_1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleRoomCreateResponse) Reset() {
	*x = BattleRoomCreateResponse{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleRoomCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleRoomCreateResponse) ProtoMessage() {}

func (x *BattleRoomCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleRoomCreateResponse.ProtoReflect.Descriptor instead.
func (*BattleRoomCreateResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *BattleRoomCreateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BattleRoomCreateResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// BattleResultRequest POST /api/battle/settle 请求体。
type BattleResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,proto3" json:"room_id,omitempty"`  // 房间 ID
	RoleId        int64                  `protobuf:"varint,2,opt,name=role_id,proto3" json:"role_id,omitempty"` // 上报者角色 ID
	Win           bool                   `protobuf:"varint,3,opt,name=win,proto3" json:"win,omitempty"`         // 是否胜利
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`     // 本局得分
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleResultRequest) Reset() {
	*x = BattleResultRequest{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleResultRequest) ProtoMessage() {}

func (x *BattleResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleResultRequest.ProtoReflect.Descriptor instead.
func (*BattleResultRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *BattleResultRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *BattleResultRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *BattleResultRequest) GetWin() bool {
	if x != nil {
		return x.Win
	}
	return false
}

func (x *BattleResultRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// BattleResultResponse POST /api/battle/settle 响应体。
type BattleResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0=成功；1003 房间不存在
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleResultResponse) Reset() {
	*x = BattleResultResponse{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleResultResponse) ProtoMessage() {}

func (x *BattleResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleResultResponse.ProtoReflect.Descriptor instead.
func (*BattleResultResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *BattleResultResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// RankUpdateRequest POST /api/rank/update 与 NATS rank.update 消息体。
type RankUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        int32                  `protobuf:"varint,1,opt,name=zone_id,proto3" json:"zone_id,omitempty"` // 区服 ID
	RoleId        int64                  `protobuf:"varint,2,opt,name=role_id,proto3" json:"role_id,omitempty"` // 角色 ID
	Score         int64                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`     // 榜单分数（ZSET score）
	Board         string                 `protobuf:"bytes,4,opt,name=board,proto3" json:"board,omitempty"`      // 榜类型，如 dungeon、level
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankUpdateRequest) Reset() {
	*x = RankUpdateRequest{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankUpdateRequest) ProtoMessage() {}

func (x *RankUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankUpdateRequest.ProtoReflect.Descriptor instead.
func (*RankUpdateRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *RankUpdateRequest) GetZoneId() int32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *RankUpdateRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RankUpdateRequest) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RankUpdateRequest) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

// MailSendRequest POST /api/mail/send 与 NATS mail.send 消息体。
type MailSendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,proto3" json:"role_id,omitempty"` // 收件人
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`      // 邮件标题
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`  // 正文
	Items         string                 `protobuf:"bytes,4,opt,name=items,proto3" json:"items,omitempty"`      // 附件奖励串，如 gold:100,potion:1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailSendRequest) Reset() {
	*x = MailSendRequest{}
	mi := &file_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailSendRequest) ProtoMessage() {}

func (x *MailSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailSendRequest.ProtoReflect.Descriptor instead.
func (*MailSendRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *MailSendRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *MailSendRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MailSendRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MailSendRequest) GetItems() string {
	if x != nil {
		return x.Items
	}
	return ""
}

// PayNotifyRequest POST /api/pay/notify 支付回调请求体。
type PayNotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,proto3" json:"order_id,omitempty"`     // 订单号
	RoleId        int64                  `protobuf:"varint,2,opt,name=role_id,proto3" json:"role_id,omitempty"`      // 购买角色
	ProductId     string                 `protobuf:"bytes,3,opt,name=product_id,proto3" json:"product_id,omitempty"` // 商品 ID
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`        // 金额
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`        // 1=已支付（OrderStatusPaid）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayNotifyRequest) Reset() {
	*x = PayNotifyRequest{}
	mi := &file_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayNotifyRequest) ProtoMessage() {}

func (x *PayNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayNotifyRequest.ProtoReflect.Descriptor instead.
func (*PayNotifyRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *PayNotifyRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PayNotifyRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *PayNotifyRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *PayNotifyRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PayNotifyRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\vnewgame.api\"`\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x18\n" +
	"\azone_id\x18\x03 \x01(\x05R\azone_id\"\x8b\x01\n" +
	"\rLoginResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x18\n" +
	"\arole_id\x18\x03 \x01(\x03R\arole_id\x12\x1c\n" +
	"\tgate_addr\x18\x04 \x01(\tR\tgate_addr\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"(\n" +
	"\x10EnterGateRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"V\n" +
	"\fMatchRequest\x12\x18\n" +
	"\arole_id\x18\x01 \x01(\x03R\arole_id\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\x05R\x04mode\x12\x18\n" +
	"\azone_id\x18\x03 \x01(\x05R\azone_id\"Y\n" +
	"\rMatchResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x1a\n" +
	"\bmatch_id\x18\x02 \x01(\tR\bmatch_id\x12\x18\n" +
	"\aroom_id\x18\x03 \x01(\tR\aroom_id\"3\n" +
	"\x17BattleRoomCreateRequest\x12\x18\n" +
	"\amembers\x18\x01 \x03(\x03R\amembers\"H\n" +
	"\x18BattleRoomCreateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\aroom_id\x18\x02 \x01(\tR\aroom_id\"q\n" +
	"\x13BattleResultRequest\x12\x18\n" +
	"\aroom_id\x18\x01 \x01(\tR\aroom_id\x12\x18\n" +
	"\arole_id\x18\x02 \x01(\x03R\arole_id\x12\x10\n" +
	"\x03win\x18\x03 \x01(\bR\x03win\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\"*\n" +
	"\x14BattleResultResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\"s\n" +
	"\x11RankUpdateRequest\x12\x18\n" +
	"\azone_id\x18\x01 \x01(\x05R\azone_id\x12\x18\n" +
	"\arole_id\x18\x02 \x01(\x03R\arole_id\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x03R\x05score\x12\x14\n" +
	"\x05board\x18\x04 \x01(\tR\x05board\"q\n" +
	"\x0fMailSendRequest\x12\x18\n" +
	"\arole_id\x18\x01 \x01(\x03R\arole_id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05items\x18\x04 \x01(\tR\x05items\"\x98\x01\n" +
	"\x10PayNotifyRequest\x12\x1a\n" +
	"\border_id\x18\x01 \x01(\tR\border_id\x12\x18\n" +
	"\arole_id\x18\x02 \x01(\x03R\arole_id\x12\x1e\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\n" +
	"product_id\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06statusB\x10Z\x0enewgame/api/pbb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_messages_proto_goTypes = []any{
	(*LoginRequest)(nil),             // 0: newgame.api.LoginRequest
	(*LoginResponse)(nil),            // 1: newgame.api.LoginResponse
	(*EnterGateRequest)(nil),         // 2: newgame.api.EnterGateRequest
	(*MatchRequest)(nil),             // 3: newgame.api.MatchRequest
	(*MatchResponse)(nil),            // 4: newgame.api.MatchResponse
	(*BattleRoomCreateRequest)(nil),  // 5: newgame.api.BattleRoomCreateRequest
	(*BattleRoomCreateResponse)(nil), // 6: newgame.api.BattleRoomCreateResponse
	(*BattleResultRequest)(nil),      // 7: newgame.api.BattleResultRequest
	(*BattleResultResponse)(nil),     // 8: newgame.api.BattleResultResponse
	(*RankUpdateRequest)(nil),        // 9: newgame.api.RankUpdateRequest
	(*MailSendRequest)(nil),          // 10: newgame.api.MailSendRequest
	(*PayNotifyRequest)(nil),         // 11: newgame.api.PayNotifyRequest
}
var file_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
