// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: messages.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameForwarder_Forward_FullMethodName = "/newgame.api.GameForwarder/Forward"
)

// GameForwarderClient is the client API for GameForwarder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameForwarderClient interface {
	Forward(ctx context.Context, in *GameForwardRequest, opts ...grpc.CallOption) (*GameForwardResponse, error)
}

type gameForwarderClient struct {
	cc grpc.ClientConnInterface
}

func NewGameForwarderClient(cc grpc.ClientConnInterface) GameForwarderClient {
	return &gameForwarderClient{cc}
}

func (c *gameForwarderClient) Forward(ctx context.Context, in *GameForwardRequest, opts ...grpc.CallOption) (*GameForwardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameForwardResponse)
	err := c.cc.Invoke(ctx, GameForwarder_Forward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameForwarderServer is the server API for GameForwarder service.
// All implementations should embed UnimplementedGameForwarderServer
// for forward compatibility.
type GameForwarderServer interface {
	Forward(context.Context, *GameForwardRequest) (*GameForwardResponse, error)
}

// UnimplementedGameForwarderServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameForwarderServer struct{}

func (UnimplementedGameForwarderServer) Forward(context.Context, *GameForwardRequest) (*GameForwardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedGameForwarderServer) testEmbeddedByValue() {}

// UnsafeGameForwarderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameForwarderServer will
// result in compilation errors.
type UnsafeGameForwarderServer interface {
	mustEmbedUnimplementedGameForwarderServer()
}

func RegisterGameForwarderServer(s grpc.ServiceRegistrar, srv GameForwarderServer) {
	// If the following call panics, it indicates UnimplementedGameForwarderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameForwarder_ServiceDesc, srv)
}

func _GameForwarder_Forward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameForwarderServer).Forward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameForwarder_Forward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameForwarderServer).Forward(ctx, req.(*GameForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameForwarder_ServiceDesc is the grpc.ServiceDesc for GameForwarder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameForwarder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "newgame.api.GameForwarder",
	HandlerType: (*GameForwarderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Forward",
			Handler:    _GameForwarder_Forward_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messages.proto",
}
